version: '3'
services:
  app:
    image: $${secrets.DOCKER_HUB_USERNAME}/sol-wallet-tracker:latest
    ports:
      - "80:3000"  # Mapping the port 80 on the host to port 3000 in the container
    environment:
      - CHAT_ID=${CHAT_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - PORT=${PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - NODE_ENV=${NODE_ENV}

